CONTRACTIONS_LIST = [
    ("i am", "i'm"),
    ("you are", "you're"),
    ("we are", "we're"),
    ("they are", "they're"),
    ("who are", "who're"),
    ("i have", "i've"),
    ("you have", "you've"),
    ("we have", "we've"),
    ("could have", "could've"),
    ("would have", "would've"),
    ("should have", "should've"),
    ("might have", "might've"),
    ("who have", "who've"),
    ("there have", "there've"),
    ("he is", "he's"),
    ("she is", "she's"),
    ("it is", "it's"),
    ("what is", "what's"),
    ("that is", "that's"),
    ("who is", "who's"),
    ("there is", "there's"),
    ("here is", "here's"),
    ("one is", "one's"),
    ("i will", "i'll"),
    ("you will", "you'll"),
    ("she will", "she'll"),
    ("he will", "he'll"),
    ("it will", "it'll"),
    ("we will", "we'll"),
    ("they will", "they'll"),
    ("that will", "that'll"),
    ("there will", "there'll"),
    ("this will", "this'll"),
    ("what will", "what'll"),
    ("who will", "who'll"),
    ("i would", "i'd"),
    ("you would", "you'd"),
    ("he would", "he'd"),
    ("she would", "she'd"),
    ("we would", "we'd"),
    ("they would", "they'd"),
    ("it would", "it'd"),
    ("there would", "there'd"),
    ("what would", "what'd"),
    ("who would", "who'd"),
    ("that would", "that'd"),
    ("let us", "let's"),
    ("cannot", "can't"),
    ("do not", "don't"),
    ("is not", "isn't"),
    ("will not", "won't"),
    ("should not", "shouldn't"),
    ("could not", "couldn't"),
    ("would not", "wouldn't"),
    ("are not", "aren't"),
    ("does not", "doesn't"),
    ("was not", "wasn't"),
    ("were not", "weren't"),
    ("has not", "hasn't"),
    ("have not", "haven't"),
    ("had not", "hadn't"),
    ("must not", "mustn't"),
    ("did not", "didn't"),
    ("might not", "mightn't"),
    ("need not", "needn't"),
]


CONTRACTION_SPACES = [(" " + x[0] + " ", " " + x[1] + " ") for x in CONTRACTIONS_LIST]

CONTRACTION_LEFT_SPACES = [(" " + x[0], " " + x[1]) for x in CONTRACTIONS_LIST]

CONTRACTION_RIGHT_SPACES = [(x[0] + " ", x[1] + " ") for x in CONTRACTIONS_LIST]
